
[en]
  title = "hancher's home"
  LanguageName = "English"
  weight = 1

[zh]
title = "寒澈的小屋"
LanguageName = "chinese"
weight = 1

[pt]
  title = "Claridade" # just for the sake of showing this is possible
  LanguageName = "Português"
  weight = 2
  